# Stale Issue / PR Action
# This actions marks issues / PRs stale when they have been inactive for a while.
#
# For configuration options see https://github.com/actions/stale

name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue seems to be stale'
        stale-pr-message: 'This PR seems to be stale'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-stale: 28 # 4 weeks
        days-before-close: 84 # 3 months (ish)